In [17]:
import numpy as np 
import pandas as pd 
import os
from itertools import combinations
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix
)
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))


/kaggle/input/competitions/playground-series-s6e7/sample_submission.csv
/kaggle/input/competitions/playground-series-s6e7/train.csv
/kaggle/input/competitions/playground-series-s6e7/test.csv
/kaggle/input/datasets/vedikagupta0/data-work-students-health-risk/preprocessed_students-health-risk-pred-dataset.csv


In [18]:
df = pd.read_csv('/kaggle/input/datasets/vedikagupta0/data-work-students-health-risk/preprocessed_students-health-risk-pred-dataset.csv')

In [19]:
df.head()

,id,health_condition,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,diet_type,...,sleep_quality,physical_activity_level,smoking_alcohol,gender,diet_type_te,stress_level_te,sleep_quality_te,physical_activity_level_te,smoking_alcohol_te,gender_te
0,0,2,5.22,70.6,25.66,2174,1326,19.8,1.86,1.0,...,1.0,0.0,2.0,0.0,2.796325,2.714307,2.802041,2.914857,2.814003,2.800322
1,1,3,5.53,71.3,25.84,1966,9891,49.9,1.26,2.0,...,1.0,1.0,2.0,0.5,2.816216,2.596113,2.802041,2.908374,2.814003,2.809136
2,2,2,5.29,75.4,24.54,2688,14216,38.1,1.60,1.0,...,0.0,2.0,2.0,1.0,2.796325,2.714307,2.794944,2.571482,2.814003,2.794403
3,3,2,4.70,77.2,23.13,2630,7174,59.9,2.02,1.0,...,1.0,2.0,1.0,0.0,2.796325,2.714307,2.802041,2.571482,2.800697,2.800322
4,4,3,7.23,73.4,28.44,2560,6584,46.0,2.25,1.0,...,1.0,0.0,-1.0,1.0,2.796325,2.801476,2.802041,2.914857,2.799139,2.794403


In [20]:
df.shape

(690088, 21)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690088 entries, 0 to 690087
Data columns (total 21 columns):
 #   Column                      Non-Null Count   Dtype  
---  ------                      --------------   -----  
 0   id                          690088 non-null  int64  
 1   health_condition            690088 non-null  int64  
 2   sleep_duration              690088 non-null  float64
 3   heart_rate                  690088 non-null  float64
 4   bmi                         690088 non-null  float64
 5   calorie_expenditure         690088 non-null  int64  
 6   step_count                  690088 non-null  int64  
 7   exercise_duration           690088 non-null  float64
 8   water_intake                690088 non-null  float64
 9   diet_type                   690088 non-null  float64
 10  stress_level                690088 non-null  float64
 11  sleep_quality               690088 non-null  float64
 12  physical_activity_level     690088 non-null  float64
 13  smoking_alcoho

In [22]:
df.describe()

,id,health_condition,sleep_duration,heart_rate,bmi,calorie_expenditure,step_count,exercise_duration,water_intake,diet_type,...,sleep_quality,physical_activity_level,smoking_alcohol,gender,diet_type_te,stress_level_te,sleep_quality_te,physical_activity_level_te,smoking_alcohol_te,gender_te
count,690088.00000,690088.000000,690088.000000,690088.000000,690088.000000,690088.000000,690088.000000,690088.000000,690088.000000,690088.000000,...,690088.000000,690088.000000,690088.000000,690088.000000,690088.000000,690088.000000,690088.000000,690088.000000,690088.000000,690088.000000
mean,345043.50000,2.800996,6.992454,75.096524,22.984976,2226.614548,8618.353697,38.754698,2.187958,1.470243,...,0.821494,0.883516,0.922872,0.463498,2.800996,2.800996,2.800996,2.800996,2.800996,2.800996
std,199211.39062,0.524174,1.146529,8.128577,2.456669,333.963538,3889.614751,14.668327,0.501896,0.476362,...,0.954823,0.908474,0.895782,0.485429,0.011117,0.160701,0.004378,0.155094,0.010315,0.005922
min,0.00000,1.000000,3.000000,50.000000,16.000000,1200.000000,1002.000000,0.000000,0.500000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,2.790200,2.596113,2.794944,2.571482,2.788294,2.794403
25%,172521.75000,3.000000,6.300000,69.500000,21.380000,2068.000000,5460.000000,29.300000,1.870000,1.000000,...,0.000000,0.000000,0.000000,0.000000,2.790200,2.714307,2.794944,2.571482,2.788294,2.794403
50%,345043.50000,3.000000,6.991299,75.098252,22.987463,2233.000000,8735.000000,39.200000,2.179271,1.500000,...,1.000000,1.000000,1.000000,0.500000,2.796325,2.714307,2.802041,2.908374,2.800697,2.800322
75%,517565.25000,3.000000,7.680000,80.600000,24.630000,2438.000000,12089.000000,49.300000,2.470000,2.000000,...,2.000000,2.000000,2.000000,1.000000,2.816216,2.990936,2.806028,2.914857,2.814003,2.809136
max,690087.00000,3.000000,10.000000,107.700000,34.820000,3580.000000,14999.000000,99.800000,4.720000,2.000000,...,2.000000,2.000000,2.000000,1.000000,2.816693,2.990936,2.806028,2.914857,2.814003,2.809136


In [23]:
id_col = ['id']
target = ['health_condition']

In [25]:
df['exercise_or_not'] = df['exercise_duration']>0

In [26]:
df['is_normal_heartrate'] = (df['heart_rate']>60) & (df['heart_rate']<100)

In [27]:
str_cols=['diet_type', 'stress_level', 'sleep_quality', 'physical_activity_level',
       'smoking_alcohol', 'gender']

In [28]:
for col in str_cols:
    df[f"{col}_missing_ind"] = df[col]==-1

In [29]:
int_cols = [
    'sleep_duration',
    'heart_rate',
    'bmi',
    'calorie_expenditure',
    'step_count',
    'water_intake'
]

for col1, col2 in combinations(int_cols, 2):
    df[f"{col1}_by_{col2}"] = df[col1] / df[col2].replace(0, np.nan)

In [30]:
X = df.drop("health_condition", axis=1)
y = df["health_condition"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

scaler = StandardScaler()

X_train_scaled = pd.DataFrame(
    scaler.fit_transform(X_train),
    columns=X_train.columns,
    index=X_train.index
)

X_test_scaled = pd.DataFrame(
    scaler.transform(X_test),
    columns=X_test.columns,
    index=X_test.index
)

In [31]:
X_test_scaled.isnull().sum()

id                                       0
sleep_duration                           0
heart_rate                               0
bmi                                      0
calorie_expenditure                      0
step_count                               0
exercise_duration                        0
water_intake                             0
diet_type                                0
stress_level                             0
sleep_quality                            0
physical_activity_level                  0
smoking_alcohol                          0
gender                                   0
diet_type_te                             0
stress_level_te                          0
sleep_quality_te                         0
physical_activity_level_te               0
smoking_alcohol_te                       0
gender_te                                0
exercise_or_not                          0
is_normal_heartrate                      0
diet_type_missing_ind                    0
stress_leve

In [37]:
logreg = LogisticRegression(
    max_iter=5000,
    random_state=42,
    multi_class="multinomial"
)

logreg.fit(X_train_scaled, y_train)

y_pred = logreg.predict(X_test_scaled)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


In [42]:
coef_df = pd.DataFrame({
    "feature": X_train_scaled.columns,
    "coefficient": logreg.coef_[0]
}).sort_values("coefficient", key=abs, ascending=False)

print(coef_df.head(50))

                                  feature  coefficient
9                            stress_level    -2.808343
31           sleep_duration_by_step_count    -1.984853
17             physical_activity_level_te    -1.896362
1                          sleep_duration     1.882020
23               stress_level_missing_ind    -1.761792
35               heart_rate_by_step_count     0.737885
38                      bmi_by_step_count     0.637273
30  sleep_duration_by_calorie_expenditure    -0.566056
40      calorie_expenditure_by_step_count     0.510286
15                        stress_level_te    -0.498279
29                  sleep_duration_by_bmi     0.482540
11                physical_activity_level    -0.422039
3                                     bmi    -0.403038
28           sleep_duration_by_heart_rate     0.393911
10                          sleep_quality     0.313901
34      heart_rate_by_calorie_expenditure     0.245920
37             bmi_by_calorie_expenditure     0.241365
18        

In [39]:
from sklearn.metrics import (
    balanced_accuracy_score,
    classification_report,
    confusion_matrix
)

y_pred = logreg.predict(X_test_scaled)

print("Balanced Accuracy:",
      balanced_accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Balanced Accuracy: 0.8458105811936316

Classification Report:
              precision    recall  f1-score   support

           1       0.86      0.78      0.82      7961
           2       0.89      0.77      0.83     11545
           3       0.96      0.98      0.97    118512

    accuracy                           0.95    138018
   macro avg       0.90      0.85      0.87    138018
weighted avg       0.95      0.95      0.95    138018


Confusion Matrix:
[[  6232     30   1699]
 [    13   8917   2615]
 [  1009   1095 116408]]


In [40]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    logreg,
    X_train_scaled,
    y_train,
    cv=5,
    scoring="balanced_accuracy"
)

print("CV Balanced Accuracy:", scores.mean())
print("Fold Scores:", scores)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and wi

CV Balanced Accuracy: 0.8421073541708969
Fold Scores: [0.8438544  0.83973854 0.84138492 0.84253855 0.84302035]


In [41]:
y.value_counts()

health_condition
3    592561
2     57724
1     39803
Name: count, dtype: int64

# we need to deal with this imbalance.